SELECT MAX(id) FROM Si.users;

SELECT MAX(id) FROM Si.users;

ALTER SEQUENCE SI.Users_id_seq RESTART WITH 1159;

ALTER SEQUENCE SI.Comments_id_seq RESTART WITH 1500;

ALTER SEQUENCE Si.terms_id_seq RESTART WITH 3779;