"""empty message

Revision ID: 22fbeb50ad82
Revises: 926c9f6ec0e1
Create Date: 2022-05-24 02:25:04.618321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fbeb50ad82'
down_revision = '926c9f6ec0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('definition_html', sa.Text(), nullable=True))
    op.add_column('terms', sa.Column('examples_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'examples_html')
    op.drop_column('terms', 'definition_html')
    # ### end Alembic commands ###
