"""empty message

Revision ID: 45593e8774b6
Revises: e69e31ae9393
Create Date: 2022-08-31 17:13:56.036440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45593e8774b6'
down_revision = 'e69e31ae9393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_sets',
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['termsets.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], )
    )
    op.drop_constraint('terms_term_set_fkey', 'terms', type_='foreignkey')
    op.drop_column('terms', 'term_set')
    op.add_column('termsets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('termsets', sa.Column('name', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'termsets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'termsets', type_='foreignkey')
    op.drop_column('termsets', 'name')
    op.drop_column('termsets', 'user_id')
    op.add_column('terms', sa.Column('term_set', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('terms_term_set_fkey', 'terms', 'termsets', ['term_set'], ['id'])
    op.drop_table('term_sets')
    # ### end Alembic commands ###
