name: Test Term Availability

on:
  push:
    branches:
      - main
      - dev

jobs:
  check-term:
    runs-on: ubuntu-latest
    steps:
      - name: Set TERM_URL based on branch
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "TERM_URL=https://yamz.net/term/ark:99152/h8072" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "TERM_URL=https://yamz-dev.yamz.net/term/ark:99152/h8072" >> $GITHUB_ENV
          else
            echo "TERM_URL=https://yamz.net/term/ark:99152/h8072" >> $GITHUB_ENV
          fi

      - name: Print which URL is being checked
        run: echo "Checking $TERM_URL"

      - name: Check term availability
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" "$TERM_URL")
          if [ "$status" = "200" ]; then
            echo "Term is available at $TERM_URL"
          else
            echo "Term is NOT available at $TERM_URL (HTTP status: $status)"
            exit 1
          fi
